---
abstract: 'weave your Pod together from configuration and Dist::Zilla'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100651'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-PodWeaver
requires:
  Dist::Zilla::Role::FileMunger: 0
  File::Find::Rule: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Autobox: 0
  PPI: 0
  Pod::Elemental: 0
  Pod::Elemental::PerlMunger: 0
  Pod::Elemental::Selectors: 0
  Pod::Elemental::Transformer::Nester: 0
  Pod::Elemental::Transformer::Pod5: 0
  Pod::Weaver: 3.100650
  Pod::Weaver::Config::Assembler: 0
  Test::More: 0
  namespace::autoclean: 0
resources:
  repository: git://git.codesimply.com/Dist-Zilla-Plugin-PodWeaver.git
version: 3.100650
